WF.Web/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WF.Business.Model;
using WF.Business.Workflow;
using WF.Web.Helpers;
using WF.Web.Models;
using System.Threading;
using AutoMapper;
using WF.Business.DataAccess;
using Microsoft.AspNetCore.Mvc;

namespace WF.Web.Controllers
{
    public class DocumentController : Controller
    {
        private readonly IDocumentRepository _documentRepository;
        private readonly IWorkflowSchemeRepository _workflowSchemeRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IMapper _mapper;

        public DocumentController(IDocumentRepository documentRepository, IWorkflowSchemeRepository workflowSchemeRepository, IEmployeeRepository employeeRepository, IMapper mapper)
        {
            _documentRepository = documentRepository;
            _workflowSchemeRepository = workflowSchemeRepository;
            _employeeRepository = employeeRepository;
            _mapper = mapper;
        }

        #region Index
        public ActionResult Index(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            return View(new DocumentListModel()
            {
                Page = page,
                PageSize = pageSize,
                Docs = _documentRepository.Get(out count, page, pageSize).Select(c => GetDocumentModel(c)).ToList(),
                Count = count,
            });
        }

        public ActionResult WorkflowScheme(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            List<WorkflowSchemeDetails> dataWorkflowScheme = _workflowSchemeRepository.Get(out count, page, pageSize).Select(c => GetWorkflowSchemeModel(c)).ToList();
            int i = 1;
            foreach (var item in dataWorkflowScheme)
            {
                item.STT = i;
                i++;
            }
            return View(new WorkflowListModel()
            {
                Page = page,
                PageSize = pageSize,
                WorkflowSchemeData = dataWorkflowScheme,
                Count = count,
            });
        }

        public ActionResult Inbox(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            return View("Index", new DocumentListModel()
            {
                Page = page,
                PageSize = pageSize,
                Docs = _documentRepository.GetInbox(CurrentUserSettings.GetCurrentUser(HttpContext), out count, page, pageSize)
                        .Select(c => GetDocumentModel(c)).ToList(),
                Count = count,
            });
        }

        public ActionResult Outbox(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            return View("Index", new DocumentListModel()
            {
                Page = page,
                PageSize = pageSize,
                Docs = _documentRepository.GetOutbox(CurrentUserSettings.GetCurrentUser(HttpContext), out count, page, pageSize)
                        .Select(c => GetDocumentModel(c)).ToList(),
                Count = count,
            });
        }
        #endregion

        #region Edit
        public ActionResult Edit(Guid? Id, string SchemeName)
        {
            DocumentModel model = null;

            if (Id.HasValue)
            {
                var d = _documentRepository.Get(Id.Value);
                if (d != null)
                {
                    CreateWorkflowIfNotExists(d.SchemeName, Id.Value);

                    var h = _documentRepository.GetHistory(Id.Value);
                    model = new DocumentModel()
                    {
                        Id = d.Id,
                        AuthorId = d.AuthorId,
                        AuthorName = d.Author.UserName,
                        Comment = d.Comment,
                        ManagerId = d.ManagerId,
                        ManagerName = d.ManagerId.HasValue ? d.Manager.UserName : string.Empty,
                        Name = d.Name,
                        Number = d.Number,
                        StateName = d.StateName,
                        Sum = d.Sum,
                        Commands = GetCommands(Id.Value),
                        AvailiableStates = GetStates(Id.Value),
                        HistoryModel = new DocumentHistoryModel { Items = h }
                    };
                }

            }
            else
            {
                Guid userId = CurrentUserSettings.GetCurrentUser(HttpContext);
                var intState = WorkflowInit.Runtime.GetInitialState(SchemeName);
                model = new DocumentModel()
                {
                    AuthorId = userId,
                    AuthorName = _employeeRepository.GetNameById(userId),
                    StateName = "Vacation request created"
                };
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Guid? Id, DocumentModel model, string button)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Document doc = _mapper.Map<Document>(model);

            try
            {
                doc = _documentRepository.InsertOrUpdate(doc);

                if (doc == null)
                {
                    ModelState.AddModelError("", "Row not found!");
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                var sb = new StringBuilder("Ошибка сохранения. " + ex.Message);
                if (ex.InnerException != null)
                    sb.AppendLine(ex.InnerException.Message);
                ModelState.AddModelError("", sb.ToString());
                return View(model);
            }

            if (button == "SaveAndExit")
                return RedirectToAction("Index");
            if (button != "Save")
            {
                ExecuteCommand(doc.Id, button, model);
            }
            return RedirectToAction("Edit", new { doc.Id });

        }
        #endregion

        #region Delete
        public ActionResult DeleteRows(Guid[] ids)
        {
            if (ids == null || ids.Length == 0)
                return Content("Items not selected");

            try
            {
                _documentRepository.Delete(ids);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

            return Content("Rows deleted");
        }

        public ActionResult DeleteScheme(string[] ids)
        {
            if (ids == null || ids.Length == 0)
                return Content("Items not selected");

            try
            {
                string rs = _documentRepository.DeleteScheme(ids);
                return Content(rs);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }            
        }
        #endregion

        #region Workflow
        private DocumentCommandModel[] GetCommands(Guid id)
        {
            var result = new List<DocumentCommandModel>();
            var commands = WorkflowInit.Runtime.GetAvailableCommands(id, CurrentUserSettings.GetCurrentUser(HttpContext).ToString());
            foreach (var workflowCommand in commands)
            {
                if (result.Count(c => c.key == workflowCommand.CommandName) == 0)
                    result.Add(new DocumentCommandModel() { key = workflowCommand.CommandName, value = workflowCommand.LocalizedName, Classifier = workflowCommand.Classifier });
            }
            return result.ToArray();
        }

        private Dictionary<string, string> GetStates(Guid id)
        {

            var result = new Dictionary<string, string>();
            var states = WorkflowInit.Runtime.GetAvailableStateToSet(id);
            foreach (var state in states)
            {
                if (!result.ContainsKey(state.Name))
                    result.Add(state.Name, state.VisibleName);
            }
            return result;

        }

        private void ExecuteCommand(Guid id, string commandName, DocumentModel document)
        {
            var currentUser = CurrentUserSettings.GetCurrentUser(HttpContext).ToString();

            if (commandName.Equals("SetState", StringComparison.InvariantCultureIgnoreCase))
            {
                if (string.IsNullOrEmpty(document.StateNameToSet))
                    return;

                WorkflowInit.Runtime.SetState(id, currentUser, currentUser, document.StateNameToSet, new Dictionary<string, object> { { "Comment", document.Comment } });
                return;
            }

            var commands = WorkflowInit.Runtime.GetAvailableCommands(id, currentUser);

            var command =
                commands.FirstOrDefault(
                    c => c.CommandName.Equals(commandName, StringComparison.CurrentCultureIgnoreCase));

            if (command == null)
                return;

            if (command.Parameters.Count(p => p.ParameterName == "Comment") == 1)
                command.Parameters.Single(p => p.ParameterName == "Comment").Value = document.Comment ?? string.Empty;

            WorkflowInit.Runtime.ExecuteCommand(command, currentUser, currentUser);
        }

        private void CreateWorkflowIfNotExists(string schemeName, Guid id)
        {
            if (WorkflowInit.Runtime.IsProcessExists(id))
                return;

            WorkflowInit.Runtime.CreateInstance(schemeName, id);
        }

        #endregion

        public ActionResult RecalcInbox()
        {
            var newThread = new Thread(WorkflowInit.RecalcInbox);
            newThread.Start();
            return Content("Calculating inbox started!");
        }

        private DocumentModel GetDocumentModel(Document d)
        {
            return new DocumentModel()

WF.Web/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WF.Business.DataAccess;
using WF.Business.Model;
using WF.Web.Models;

namespace WF.Web.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ISettingsProvider _settingsProvider;

        public SettingsController(ISettingsProvider settingsProvider)
        {
            _settingsProvider = settingsProvider;
        }

        public ActionResult Edit()
        {
            return View(GetModel());
        }

        #region Other
        private SettingsModel GetModel()
        {
            var model = new SettingsModel
            {
                SchemeName = "SimpleWF"
            };

            var config = _settingsProvider.GetSettings();
            model.Employees = config.Employees;
            model.Roles = config.Roles;
            model.StructDivision = config.StructDivision;

            return model;
        }

        public static string GenerateColumnHtml(string name, StructDivision m, List<StructDivision> Model, List<Employee> employes, ref int index, string refId)
        {
            string valuePrefix = string.Format("{0}[{1}]", name, index);

            var sb = new StringBuilder();
            string trName = string.Format("tr_{0}{1}", name, index);

            sb.AppendFormat("<tr Id='{0}' {1}>", trName,
                            string.IsNullOrEmpty(refId) ? string.Empty : string.Format("class='child-of-{0}'", refId));
            sb.AppendFormat("<input type='hidden' name='{0}.Id' value='{1}'></input>", valuePrefix, m.Id);
            sb.AppendFormat("<input type='hidden' name='{0}.ParentId' value='{1}'></input>", valuePrefix, m.ParentId);
            sb.AppendFormat("<td class='columnTree'><b>{0}</b></td>", m.Name);
            sb.AppendFormat("<td></td>");
            sb.Append("</tr>");

            foreach (var item in employes.Where(c => c.StructDivisionId == m.Id))
            {
                index++;
                sb.Append(GenerateColumnHtml(name, item, ref index, trName));
            }

            foreach (var item in Model.Where(c => c.ParentId == m.Id))
            {
                index++;
                sb.Append(GenerateColumnHtml(name, item, Model, employes, ref index, trName));
            }

            return sb.ToString();
        }

        public static string GenerateColumnHtml(string name, Employee m, ref int index, string refId)
        {
            string valuePrefix = string.Format("{0}[{1}]", name, index);

            var sb = new StringBuilder();
            string trName = string.Format("tr_{0}{1}", name, index);

            sb.AppendFormat("<tr Id='{0}' {1}>", trName,
                            string.IsNullOrEmpty(refId) ? string.Empty : string.Format("class='child-of-{0}'", refId));
            sb.AppendFormat("<input type='hidden' name='{0}.Id' value='{1}'></input>", valuePrefix, m.Id);
            sb.AppendFormat("<td class='columnTree'>");
            sb.AppendFormat("{0}", m.Name);
            sb.AppendFormat("</td>");
            sb.AppendFormat("<td>");
            sb.AppendFormat("{0}", string.Join(",", m.EmployeeRoles.Select(c => c.Role.Name).ToArray()));
            sb.AppendFormat("</td>");
            sb.Append("</tr>");

            return sb.ToString();
        }
        #endregion
    }
}

WF.Web/Views/Shared/Partial/Folders.cshtml
@using System.Linq
@using Microsoft.AspNetCore.Http.Extensions

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor ContextAccessor

@{
    int folder = 0;
    if (ContextAccessor.HttpContext != null)
    {
        if (ContextAccessor.HttpContext.Request.GetEncodedUrl().ToLower().Contains("inbox"))
        {
            folder = 1;
        }
        else if (ContextAccessor.HttpContext.Request.GetEncodedUrl().ToLower().Contains("outbox"))
        {
            folder = 2;
        }
    }
}

<div style="width: 300px; float: left;">
    <div class="ui menu">
        <a href="/" class="item">@Html.Raw(folder == 0 ? "<b>All vacation requests</b>" : "All vacation requests")</a>
        <a href="/Document/Inbox" class="item">@Html.Raw(folder == 1 ? "<b>Inbox</b>" : "Inbox")</a>
        <a href="/Document/Outbox" class="item">@Html.Raw(folder == 2 ? "<b>Outbox</b>" : "Outbox")</a>
    </div>
</div>

<script>
    function ReCalcInbox() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("RecalcInbox", "Document")",
            success: function (msg) {
                alert(msg);
            }
        });
    }

</script>

WF.Web/Views/Shared/Partial/Footer.cshtml
<div class="wfe-application-footer">
    <span style="padding-top: 20px;">
        <b>COPYRIGHT © 2019 SAVIS CORP</b>
        Official site - <a href="https://savis.com.vn">https://savis.com.vn</a>
    </span>
</div>

WF.Web/Views/Shared/Partial/Header.cshtml
@using System.Linq
@using WF.Business.Model
@using WF.Web.Helpers
@using WF.Business.DataAccess

@inject IEmployeeRepository EmployeeRepository
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor ContextAccessor

@{
    Guid currentEmployeeId = CurrentUserSettings.GetCurrentUser(ContextAccessor.HttpContext);

    if (currentEmployeeId == Guid.Empty)
    {
        IList<Employee> list = EmployeeRepository.GetAll();
        if (list != null && list.Count > 0)
        {
            currentEmployeeId = list[0].Id;
            CurrentUserSettings.SetUserInCookies(ContextAccessor.HttpContext, currentEmployeeId);
        }
    }

    var htmlAtt = new Dictionary<string, object>();
    htmlAtt.Add("class", "ui dropdown");
    htmlAtt.Add("onchange", "CurrentEmployee_OnChange(this);");


}
<script>
    function CurrentEmployee_OnChange(sender) {
        window.location.search = "CurrentEmployee=" + sender.value;
    }
</script>

<div class="ui form" style="min-width: 300px; float: right;">
    <div class="field">
        <label>Current employee</label>
        @Html.DropDownList("CurrentEmployee",
                         EmployeeRepository.GetAll().Select(item => new SelectListItem()
                         {
                             Text = string.Format("Name: {0}; StructDivision: {1}; Roles: {2}", item.Name, item.StructDivision.Name, item.GetListRoles()),
                             Value = item.Id.ToString(),
                             Selected = item.Id == currentEmployeeId
                         }).ToList(),
                        htmlAtt)
    </div>
</div>

WF.Web/Views/Shared/Partial/MainMenu.cshtml
<div class="wfe-application-mainmenu" style="height:50px">
    <div style="float:left">
        <div class="logotitle">
            @*<a href="/"><img height="32" src="@Url.Content("~/images/logo.png")" /></a>*@
        </div>
    </div>
    <div style="float:right; display:none">
        <a href="/Document/Edit" class="ui primary button">Create a vacation request</a>
        <a href="/Designer" class="ui secondary button">Designer</a>
        <a href="/" class="ui secondary button">Vacation requests</a>
        <a href="@Url.Action("Edit", "Settings")" class="ui secondary button">Settings</a>
    </div>
</div>